name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install (workspaces)
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Backend Tests
        run: npm run test --workspace backend || npm run test
      - name: Frontend Build
        run: npm run build

  arm-prebuild-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install build tooling
        run: sudo apt-get update && sudo apt-get install -y build-essential python3 make g++
      - name: Clean install
        run: npm ci --include=dev
      - name: Rebuild better-sqlite3 from source
        run: npm run rebuild:sqlite
      - name: Sanity run
        run: node -e "require('better-sqlite3'); console.log('better-sqlite3 OK')"
